'use client'

import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { useForm, useFieldArray } from 'react-hook-form'
import { useEffect, useState, useMemo } from 'react'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog'
import {
  deleteServiceAction,
  updateServiceMembersAction,
  distributeServiceAction,
} from '@/actions/service-actions'
import { toast } from 'sonner'
import { Person } from '@/types/moneyflow.types'
import { ServiceEditDialog } from './service-edit-dialog'
import { Trash2 } from 'lucide-react'
import { cn } from '@/lib/utils'

// TODO: These types should be properly defined and imported
type Service = {
  id: string
  name: string
  price: number | null
}

type ServiceMember = {
  id: string
  profile_id: string
  profile: {
    id: string
    avatar_url: string | null
    name: string
  }
  slots: number
  is_owner: boolean
}

interface ServiceCardProps {
  service: Service
  members: ServiceMember[]
  allPeople: Person[]
}

export function ServiceCard({ service, members, allPeople }: ServiceCardProps) {
  const [isDistributing, setIsDistributing] = useState(false)
  const [isDeleting, setIsDeleting] = useState(false)
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false)
  const [isAddMemberDialogOpen, setIsAddMemberDialogOpen] = useState(false)
  const [searchQuery, setSearchQuery] = useState('')
  const [nextBillDate, setNextBillDate] = useState<string>('')
  // [M2-SP1] Enhancement: Remove "Auto:" and use new default format
  const [noteFormat, setNoteFormat] = useState(`{service} {date} [{slots} slots] [{price}]`)

  const { control, watch, reset } = useForm({
    defaultValues: {
      members: members.map(m => ({
        id: m.id,
        profile_id: m.profile.id,
        slots: m.slots,
        is_owner: m.is_owner,
        profile: m.profile,
      })),
    },
  })

  const { fields, append, remove } = useFieldArray({
    control,
    name: 'members',
  })

  const watchedMembers = watch('members')

  const peopleToAdd = useMemo(() => {
    const memberIds = new Set(watchedMembers.map(m => m.profile_id))
    const filteredPeople = allPeople.filter(p => !memberIds.has(p.id))
    if (!searchQuery) {
      return filteredPeople
    }
    return filteredPeople.filter(p =>
      p.name.toLowerCase().includes(searchQuery.toLowerCase())
    )
  }, [allPeople, watchedMembers, searchQuery])

  // [M2-SP1] Enhancement: Note Preview
  const previewNote = useMemo(() => {
    // Try to find a member with > 1 slot to show a better example, otherwise use the first one
    const sampleMember = watchedMembers.find(m => m.slots > 1) || watchedMembers[0] || { profile: { name: 'Member' }, slots: 1 };

    const date = nextBillDate ? new Date(nextBillDate) : new Date();
    const monthYear = date.toLocaleString('default', { month: '2-digit', year: 'numeric' }).replace('/', '-'); // e.g., 12-2025

    const totalSlots = watchedMembers.reduce((sum, m) => sum + (Number(m.slots) || 0), 0) || 1;
    const pricePerSlot = Math.round((service.price || 0) / totalSlots);

    return noteFormat
      .replace('{service}', service.name)
      .replace('{member}', sampleMember.profile.name)
      .replace('{slots}', String(sampleMember.slots))
      .replace('{date}', monthYear)
      .replace('{price}', `${pricePerSlot.toLocaleString()}`) // [M2-SP1] Enhancement: Price with commas
      .replace('{total_slots}', String(totalSlots));
  }, [noteFormat, service.name, service.price, watchedMembers, nextBillDate]);

  const handleAddMember = (person: Person) => {
    // Check for duplicates
    if (watchedMembers.some(m => m.profile_id === person.id)) {
      toast.error(`${person.name} is already a member.`)
      return
    }

    append({
      id: '', // This will be generated by the DB
      profile_id: person.id,
      slots: 1,
      is_owner: person.is_owner ?? false,
      profile: {
        id: person.id,
        name: person.name,
        avatar_url: person.avatar_url ?? null,
      },
    })
    setIsAddMemberDialogOpen(false)
  }

  const handleDelete = async () => {
    if (window.confirm('Are you sure you want to delete this service?')) {
      setIsDeleting(true)
      const result = await deleteServiceAction(service.id)
      if (result.success) {
        toast.success('Service deleted successfully!')
      } else {
        toast.error(result.error)
      }
      setIsDeleting(false)
    }
  }

  const handleDistribute = async () => {
    setIsDistributing(true)
    const result = await distributeServiceAction(service.id, nextBillDate || undefined, noteFormat)
    if (result.success) {
      toast.success('Service distributed successfully!')
    } else {
      toast.error(result.error)
    }
    setIsDistributing(false)
  }

  // Debounced update
  useEffect(() => {
    const handler = setTimeout(() => {
      // Compare only relevant fields to avoid loops caused by changing IDs
      const hasChanges = watchedMembers.some((wm, index) => {
        const m = members[index]
        if (!m) return true // Length mismatch
        return (
          wm.profile_id !== m.profile_id ||
          wm.slots !== m.slots ||
          wm.is_owner !== m.is_owner
        )
      }) || watchedMembers.length !== members.length

      if (hasChanges) {
        updateServiceMembersAction(service.id, watchedMembers)
      }
    }, 1000)

    return () => {
      clearTimeout(handler)
    }
  }, [watchedMembers, service.id, members])

  return (
    <Card className="flex flex-col h-full">
      <CardHeader>
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            {(service as any).shop?.logo_url && (
              <img
                src={(service as any).shop.logo_url}
                alt={(service as any).shop.name}
                className="h-8 w-8 rounded-full object-cover"
              />
            )}
            <CardTitle>{service.name}</CardTitle>
          </div>
          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" onClick={() => setIsEditDialogOpen(true)}>Edit</Button>
            <Button variant="destructive" size="sm" onClick={handleDelete} disabled={isDeleting}>
              {isDeleting ? 'Deleting...' : 'Delete'}
            </Button>
            <CardDescription className="font-bold text-lg text-emerald-600">
              {service.price?.toLocaleString()} đ
            </CardDescription>
          </div>
        </div>
      </CardHeader>
      <CardContent className="flex-grow space-y-6">
        <div className="space-y-4">
          <div className="flex justify-between items-center">
            <h4 className="text-sm font-medium text-slate-500 uppercase tracking-wider">Members</h4>
            <Dialog open={isAddMemberDialogOpen} onOpenChange={setIsAddMemberDialogOpen}>
              <DialogTrigger asChild>
                <Button variant="outline" size="sm" className="h-8">+ Add Member</Button>
              </DialogTrigger>
              <DialogContent className="max-h-[80vh] overflow-y-auto">
                <DialogHeader>
                  <DialogTitle>Add Member</DialogTitle>
                </DialogHeader>
                <div className="p-4">
                  <Input
                    placeholder="Search people..."
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                  />
                </div>
                <div className="space-y-2">
                  {peopleToAdd.length === 0 ? (
                    <p className="text-center text-sm text-slate-500 py-4">No people found.</p>
                  ) : (
                    peopleToAdd.map(person => (
                      <div
                        key={person.id}
                        onClick={() => handleAddMember(person)}
                        className="p-3 hover:bg-slate-100 cursor-pointer rounded-md flex items-center gap-3 transition-colors"
                      >
                        <div className="h-8 w-8 rounded-full bg-slate-200 flex items-center justify-center text-xs font-bold text-slate-600">
                          {person.avatar_url ? (
                            <img src={person.avatar_url} alt={person.name} className="h-full w-full rounded-full object-cover" />
                          ) : (
                            person.name.charAt(0).toUpperCase()
                          )}
                        </div>
                        <span className="font-medium text-slate-700">{person.name}</span>
                      </div>
                    ))
                  )}
                </div>
              </DialogContent>
            </Dialog>
          </div>
          <div className="space-y-3">
            {fields.map((field, index) => (
              <div key={field.id} className="flex items-center gap-3 bg-slate-50 p-2 rounded-lg border border-slate-100">
                <div className="h-8 w-8 rounded-full bg-white border border-slate-200 flex items-center justify-center text-xs font-bold text-slate-600 shrink-0">
                  {field.profile.avatar_url ? (
                    <img src={field.profile.avatar_url} alt={field.profile.name} className="h-full w-full rounded-full object-cover" />
                  ) : (
                    field.profile.name.charAt(0).toUpperCase()
                  )}
                </div>
                <span className="flex-grow font-medium text-sm text-slate-700 truncate">{field.profile.name}</span>
                <div className="flex items-center gap-2">
                  <span className="text-xs text-slate-400">Slots:</span>
                  <Input
                    type="number"
                    className="w-16 h-8 text-center"
                    min={1}
                    {...control.register(`members.${index}.slots` as const)}
                  />
                  <Button
                    variant="ghost"
                    size="icon"
                    className="h-8 w-8 text-slate-400 hover:text-red-600"
                    onClick={() => remove(index)}
                  >
                    <Trash2 className="h-4 w-4" />
                  </Button>
                </div>
              </div>
            ))}
            {fields.length === 0 && (
              <p className="text-center text-sm text-slate-400 italic py-2">No members assigned.</p>
            )}
          </div>
        </div>

        <div className="space-y-4 pt-4 border-t border-slate-100">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label className="text-xs text-slate-500">Next Bill Date</Label>
              <Input
                type="date"
                value={nextBillDate}
                onChange={(e) => setNextBillDate(e.target.value)}
                className="h-9 text-xs"
              />
            </div>
            <div className="space-y-2">
              <Label className="text-xs text-slate-500">Note Template</Label>
              <Input
                value={noteFormat}
                onChange={(e) => setNoteFormat(e.target.value)}
                className="h-9 text-xs"
                placeholder="{service} {date}..."
              />
            </div>
          </div>

          {/* [M2-SP1] Enhancement: Preview Box */}
          <div className="bg-slate-50 p-2 rounded border border-slate-100">
            <p className="text-[10px] text-slate-400 font-medium mb-1">Preview:</p>
            <p className="text-xs text-slate-600 font-mono">{previewNote}</p>
          </div>

          <p className="text-[10px] text-slate-400">
            Tokens: {'{service}'}, {'{member}'}, {'{slots}'}, {'{date}'}, {'{price}'}, {'{total_slots}'}
          </p>
        </div>

      </CardContent>
      <CardFooter className="bg-slate-50 p-4 rounded-b-lg border-t border-slate-100">
        <Button
          onClick={handleDistribute}
          disabled={isDistributing || watchedMembers.length === 0}
          className="w-full bg-slate-900 hover:bg-slate-800 text-white"
        >
          {isDistributing ? 'Distributing...' : '⚡ Distribute Now'}
        </Button>
      </CardFooter>
      <ServiceEditDialog
        service={service}
        open={isEditDialogOpen}
        onOpenChange={setIsEditDialogOpen}
      />
    </Card>
  )
}
