'use client'

import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { useForm, useFieldArray } from 'react-hook-form'
import { useEffect, useState, useMemo } from 'react'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog'
import {
  deleteServiceAction,
  updateServiceMembersAction,
  distributeServiceAction,
} from '@/actions/service-actions'
import { toast } from 'sonner'
import { Person } from '@/types/moneyflow.types'
import { ServiceEditDialog } from './service-edit-dialog'

// TODO: These types should be properly defined and imported
type Service = {
  id: string
  name: string
  price: number | null
}

type ServiceMember = {
  id: string
  profile_id: string
  profile: {
    id: string
    avatar_url: string | null
    name: string
  }
  slots: number
  is_owner: boolean
}

interface ServiceCardProps {
  service: Service
  members: ServiceMember[]
  allPeople: Person[]
}

export function ServiceCard({ service, members, allPeople }: ServiceCardProps) {
  const [isDistributing, setIsDistributing] = useState(false)
  const [isDeleting, setIsDeleting] = useState(false)
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false)
  const [isAddMemberDialogOpen, setIsAddMemberDialogOpen] = useState(false)
  const [searchQuery, setSearchQuery] = useState('')

  const { control, watch, reset } = useForm({
    defaultValues: {
      members: members.map(m => ({
        id: m.id,
        profile_id: m.profile.id,
        slots: m.slots,
        is_owner: m.is_owner,
        profile: m.profile,
      })),
    },
  })

  const { fields, append, remove } = useFieldArray({
    control,
    name: 'members',
  })

  const watchedMembers = watch('members')

  const peopleToAdd = useMemo(() => {
    const memberIds = new Set(watchedMembers.map(m => m.profile_id))
    const filteredPeople = allPeople.filter(p => !memberIds.has(p.id))
    if (!searchQuery) {
      return filteredPeople
    }
    return filteredPeople.filter(p =>
      p.name.toLowerCase().includes(searchQuery.toLowerCase())
    )
  }, [allPeople, watchedMembers, searchQuery])

  const handleAddMember = (person: Person) => {
    append({
      id: '', // This will be generated by the DB
      profile_id: person.id,
      slots: 1,
      is_owner: person.is_owner ?? false,
      profile: {
        id: person.id,
        name: person.name,
        avatar_url: person.avatar_url ?? null,
      },
    })
    setIsAddMemberDialogOpen(false)
  }

  const handleDelete = async () => {
    if (window.confirm('Are you sure you want to delete this service?')) {
      setIsDeleting(true)
      const result = await deleteServiceAction(service.id)
      if (result.success) {
        toast.success('Service deleted successfully!')
      } else {
        toast.error(result.error)
      }
      setIsDeleting(false)
    }
  }

  const handleDistribute = async () => {
    setIsDistributing(true)
    const result = await distributeServiceAction(service.id)
    if (result.success) {
      toast.success('Service distributed successfully!')
    } else {
      toast.error(result.error)
    }
    setIsDistributing(false)
  }

  // Debounced update
  useEffect(() => {
    const handler = setTimeout(() => {
      if (JSON.stringify(watchedMembers) !== JSON.stringify(members)) {
        updateServiceMembersAction(service.id, watchedMembers)
      }
    }, 1000)

    return () => {
      clearTimeout(handler)
    }
  }, [watchedMembers, service.id, members])

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <CardTitle>{service.name}</CardTitle>
          </div>
          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" onClick={() => setIsEditDialogOpen(true)}>Edit</Button>
            <Button variant="destructive" size="sm" onClick={handleDelete} disabled={isDeleting}>
              {isDeleting ? 'Deleting...' : 'Delete'}
            </Button>
            <CardDescription>{service.price} đ</CardDescription>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          <div className="flex justify-between items-center">
            <h4 className="text-sm font-medium">Members</h4>
            <Dialog open={isAddMemberDialogOpen} onOpenChange={setIsAddMemberDialogOpen}>
              <DialogTrigger asChild>
                <Button variant="outline" size="sm">+ Add</Button>
              </DialogTrigger>
              <DialogContent className="max-h-[80vh] overflow-y-auto">
                <DialogHeader>
                  <DialogTitle>Add Member</DialogTitle>
                </DialogHeader>
                <div className="p-4">
                  <Input
                    placeholder="Search people..."
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                  />
                </div>
                <div className="space-y-2">
                  {peopleToAdd.map(person => (
                    <div
                      key={person.id}
                      onClick={() => handleAddMember(person)}
                      className="p-2 hover:bg-gray-100 cursor-pointer rounded-md"
                    >
                      {person.name}
                    </div>
                  ))}
                </div>
              </DialogContent>
            </Dialog>
          </div>
          <div className="space-y-2">
            {fields.map((field, index) => (
              <div key={field.id} className="flex items-center gap-2">
                <img
                  src={field.profile.avatar_url ?? '/user-placeholder.png'}
                  alt={field.profile.name}
                  className="w-8 h-8 rounded-full"
                />
                <span className="flex-grow">{field.profile.name}</span>
                <Input
                  type="number"
                  className="w-20"
                  {...control.register(`members.${index}.slots` as const)}
                />
              </div>
            ))}
          </div>
        </div>
      </CardContent>
      <CardFooter className="flex justify-between">
        <div>
          <p className="text-sm text-muted-foreground">Next Bill: N/A</p>
        </div>
        <Button
          onClick={handleDistribute}
          disabled={isDistributing || watchedMembers.length === 0}
        >
          {isDistributing ? 'Distributing...' : '⚡ Distribute Now'}
        </Button>
      </CardFooter>
      <ServiceEditDialog
        service={service}
        open={isEditDialogOpen}
        onOpenChange={setIsEditDialogOpen}
      />
    </Card>
  )
}
